"use client";

import { useState } from "react";
import { Khand } from "next/font/google";
import "../styles/globals.css";
import NavBar from "../app/components/NavBar.js";
import SearchBar from "./components/SearchBar.js";
import Result from "./components/result";
import About from "./components/about";
import React from "react";

const khand = Khand({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-khand",
});

// export const metadata = {
//   title: "Nomito",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [showSearchBar, setShowSearchBar] = useState(false);
  const [ingredients, setIngredients] = useState("");
  const [navTitle, setNavTitle] = useState("Home");
  const [showAbout, setShowAbout] = useState(true);
  const [resetResult, setResetResult] = useState(false);

  const handleGoHome = () => {
    setNavTitle("Home");
    setShowSearchBar(false);
    setShowAbout(true);
    setIngredients("");
    setResetResult((prev) => !prev);
  };

  return (
    <html lang="en">
      <body className={`${khand.variable}`}>
        <NavBar
          onShowSearchBar={() => {
            setShowSearchBar(true);
            setNavTitle("Recipes by Ingredients");
            setShowAbout(false);
          }}
          onSetTitle={(title) => {
            setNavTitle(title);
            setShowAbout(false);
          }}
          setShowSearchBar={setShowSearchBar}
          setShowAbout={setShowAbout}
          navTitle={navTitle}
          onGoHome={handleGoHome}
        />
        {showSearchBar && <SearchBar onSearch={setIngredients} />}
        <Result ingredients={ingredients} resetTrigger={resetResult} />
        {children}
        {showAbout && <About />}
      </body>
    </html>
  );
}
