import { Geist, Geist_Mono } from "next/font/google";
import { Khand } from "next/font/google";
import "../styles/globals.css";
import NavBar from "../app/components/NavBar";

const khand = Khand({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-khand",
});

export const metadata = {
  title: "Nomito",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${khand.variable}`}>
        {children}
        <NavBar></NavBar>
      </body>
    </html>
  );
}
